apiVersion: v1
kind: ConfigMap
metadata:
  name: nodeguardian-config
  namespace: nodeguardian-system
  labels:
    app: nodeguardian
    component: config
data:
  # 统一配置文件 - 支持Python脚本
  config.json: |
    {
      "email": {
        "smtpServer": "smtp.gmail.com",
        "smtpPort": 587,
        "username": "",
        "password": "",
        "from": "nodeguardian@example.com",
        "to": ["admin@example.com"],
        "useTLS": true,
        "useSSL": false
      },
      "prometheus": {
        "url": "http://prometheus-k8s.monitoring.svc:9090",
        "timeout": "30s",
        "retries": 3,
        "queryTimeout": "60s",
        "maxSamples": 10000
      },
      "alert": {
        "webhookUrl": "",
        "defaultChannels": ["log", "email"],
        "retryAttempts": 3,
        "retryDelay": "5s",
        "batchSize": 10,
        "batchTimeout": "30s"
      },
      "monitoring": {
        "defaultCheckInterval": "30s",
        "defaultCooldownPeriod": "10m",
        "metricsServerUrl": "https://kubernetes.default.svc:443/apis/metrics.k8s.io/v1beta1",
        "maxConcurrentChecks": 10,
        "healthCheckInterval": "60s"
      },
      "log": {
        "level": "INFO",
        "format": "json",
        "output": "stdout",
        "maxSize": "100MB",
        "maxBackups": 3,
        "maxAge": "7d"
      },
      "node": {
        "defaultTaintKey": "nodeguardian.io/status",
        "defaultTaintEffect": "NoSchedule",
        "defaultLabelPrefix": "nodeguardian.io/",
        "excludeNamespaces": ["kube-system", "kube-public", "monitoring"],
        "maxEvictionPods": 10
      },
      "python": {
        "enabled": true,
        "scriptsPath": "/scripts",
        "logLevel": "INFO",
        "timeout": "300s",
        "maxRetries": 3
      }
    }

---
apiVersion: v1
kind: Secret
metadata:
  name: nodeguardian-secrets
  namespace: nodeguardian-system
  labels:
    app: nodeguardian
    component: secrets
type: Opaque
data:
  # Base64编码的敏感配置
  # 使用以下命令生成base64编码:
  # echo -n "your-email@gmail.com" | base64
  # echo -n "your-app-password" | base64
  email-username: ""  # 替换为实际的base64编码用户名
  email-password: ""  # 替换为实际的base64编码密码
  webhook-url: ""     # 替换为实际的base64编码webhook URL
