apiVersion: v1
kind: ConfigMap
metadata:
  name: nodeguardian-email-config
  namespace: nodeguardian-system
data:
  # 邮件配置示例
  email-config.json: |
    {
      "smtpServer": "smtp.gmail.com",
      "smtpPort": 587,
      "username": "your-email@gmail.com",
      "password": "your-app-password",
      "from": "nodeguardian@yourdomain.com",
      "to": ["admin@yourdomain.com", "ops@yourdomain.com"],
      "useTLS": true,
      "useSSL": false
    }

---
apiVersion: v1
kind: Secret
metadata:
  name: nodeguardian-email-secret
  namespace: nodeguardian-system
type: Opaque
data:
  # Base64编码的邮件配置
  # echo -n "your-email@gmail.com" | base64
  username: eW91ci1lbWFpbEBnbWFpbC5jb20=
  # echo -n "your-app-password" | base64  
  password: eW91ci1hcHAtcGFzc3dvcmQ=

---
apiVersion: nodeguardian.io/v1
kind: NodeGuardianRule
metadata:
  name: email-alert-example
  namespace: nodeguardian-system
spec:
  # 节点选择器
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/worker: ""
  
  # 监控条件
  conditions:
    - metric: "memoryUtilizationPercent"
      operator: "GreaterThan"
      value: 85
      duration: "2m"
  
  # 执行动作
  actions:
    - type: "alert"
      alert:
        enabled: true
        template: "high-memory-alert"
        channels: ["email", "webhook", "log"]
        # 邮件特定配置（可选）
        emailConfig: |
          {
            "smtpServer": "smtp.gmail.com",
            "smtpPort": 587,
            "from": "alerts@yourdomain.com",
            "to": ["admin@yourdomain.com"],
            "useTLS": true
          }
  
  # 监控配置
  monitoring:
    checkInterval: "30s"
    cooldownPeriod: "10m"
    metricsSource:
      type: "prometheus"
      url: "http://prometheus-k8s.monitoring.svc:9090"

---
apiVersion: nodeguardian.io/v1
kind: AlertTemplate
metadata:
  name: high-memory-alert
  namespace: nodeguardian-system
spec:
  title: "高内存使用告警 - {{ .nodeName }}"
  summary: |
    节点 {{ .nodeName }} 内存使用率过高
    
    当前内存使用率: {{ .metrics.memoryUtilizationPercent }}%
    阈值: 85%
    
    请及时处理。
  description: |
    详细信息:
    - 节点: {{ .nodeName }}
    - 内存使用率: {{ .metrics.memoryUtilizationPercent }}%
    - CPU使用率: {{ .metrics.cpuUtilizationPercent }}%
    - 磁盘使用率: {{ .metrics.diskUtilizationPercent }}%
    - 触发时间: {{ .timestamp }}
    
    建议操作:
    1. 检查节点上的高内存使用进程
    2. 考虑重启相关Pod
    3. 检查是否有内存泄漏
  channels: ["email", "webhook", "log"]
  variables:
    nodeName: "string"
    metrics: "object"
    timestamp: "string"
